version: '3.9'
services:
  fix-redis-volume-ownership: # This service is to authorise redis-master with ownership permissions
    image: 'bitnami/redis:latest'
    container_name: ownership
    user: root
    command: chown -R 1001:1001 /bitnami
    volumes:
      - /home/services/redis/master/:/bitnami
      - ./etc/conf/redis.conf:/opt/bitnami/redis/conf/redis.conf

  redis-master:
    image: 'bitnami/redis:latest'
    container_name: redis_master
    hostname: redis_master
    restart: always
    ports:
      - '6379:6379'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=YOUR_PASSWORD_REFDIS
    sysctls:
      - net.core.somaxconn=65535
    volumes:
      - /home/services/redis/master/:/bitnami
      - ./etc/conf/redis.conf:/opt/bitnami/redis/conf/redis.conf

    networks:
      - my_service
      
networks:
  my_service:
    external: true
